# Run mtk-openwrt-feeds autobuild script for prepare
name: MTK Feeds Autobuild

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Build Target'
        required: false
        default: 'filogic-mac80211-mt7988_rfb-mt7996'
  schedule:
    - cron: '0 0 * * 1,3,5'

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev \
          python3-setuptools rsync swig unzip zlib1g-dev file wget -y

      - name: Checkout OpenWrt
        run: sudo git clone --branch openwrt-24.10 https://github.com/openwrt/openwrt.git /mnt/openwrt

      - name: Clone mtk-openwrt-feeds
        run: sudo git clone --branch master https://git01.mediatek.com/openwrt/feeds/mtk-openwrt-feeds /mnt/mtk-openwrt-feeds

      - name: Run Autobuild Prepare Script
        run: |
          cd /mnt/openwrt
          sudo bash ../mtk-openwrt-feeds/autobuild/unified/autobuild.sh ${{ github.event.inputs.target || 'filogic-mac80211-mt7988_rfb-mt7996' }} prepare

      - name: Run Autobuild
        run: |
          cd /mnt/openwrt
          export FORCE_UNSAFE_CONFIGURE=1
          sudo -E bash ../mtk-openwrt-feeds/autobuild/unified/autobuild.sh ${{ github.event.inputs.target || 'filogic-mac80211-mt7988_rfb-mt7996' }} build
      
      - name: Save Image
        uses: actions/upload-artifact@v4
        with:
          name: filogic
          path: /mnt/openwrt/bin/targets/mediatek/filogic
